-- They do quality stuff, but not really a fan of the studio.
CREATE TRIGGER Sailor_OnUnitOperationAvailabilityEffect
AFTER INSERT ON GameEffects WHEN New.Type = 'EFFECT_CHANGE_UNIT_OPERATION_AVAILABILITY'
BEGIN
INSERT OR REPLACE INTO Types (Type, Kind) VALUES ('MODIFIER_SAILOR_WATCHTOWER_DISABLE_OPS', 'KIND_MODIFIER');
INSERT OR REPLACE INTO DynamicModifiers (ModifierType, CollectionType, EffectType)
VALUES	('MODIFIER_SAILOR_WATCHTOWER_DISABLE_OPS', 'COLLECTION_OWNER', 'EFFECT_CHANGE_UNIT_OPERATION_AVAILABILITY');

INSERT OR REPLACE INTO UnitAbilityModifiers	(UnitAbilityType, ModifierId) 
VALUES	('ABILITY_SAILOR_WATCHTOWER_DISABLE_OPS', 'SAILOR_WATCHTOWER_DISABLE_PLANT'),
		('ABILITY_SAILOR_WATCHTOWER_DISABLE_OPS', 'SAILOR_WATCHTOWER_DISABLE_DECONTAMINATE'),
		('ABILITY_SAILOR_WATCHTOWER_DISABLE_OPS', 'SAILOR_WATCHTOWER_DISABLE_HARVEST'),
		('ABILITY_SAILOR_WATCHTOWER_DISABLE_OPS', 'SAILOR_WATCHTOWER_DISABLE_FEATURE_REMOVAL');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType)
VALUES	('SAILOR_WATCHTOWER_DISABLE_PLANT', 'MODIFIER_SAILOR_WATCHTOWER_DISABLE_OPS'),
		('SAILOR_WATCHTOWER_DISABLE_DECONTAMINATE', 'MODIFIER_SAILOR_WATCHTOWER_DISABLE_OPS'),
		('SAILOR_WATCHTOWER_DISABLE_HARVEST', 'MODIFIER_SAILOR_WATCHTOWER_DISABLE_OPS'),
		('SAILOR_WATCHTOWER_DISABLE_FEATURE_REMOVAL', 'MODIFIER_SAILOR_WATCHTOWER_DISABLE_OPS');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name,	Value)
VALUES	('SAILOR_WATCHTOWER_DISABLE_PLANT', 'OperationType', 'UNITOPERATION_PLANT_FOREST'),
		('SAILOR_WATCHTOWER_DISABLE_PLANT', 'Available', 0),
		('SAILOR_WATCHTOWER_DISABLE_DECONTAMINATE', 'OperationType', 'UNITOPERATION_CLEAR_CONTAMINATION'),
		('SAILOR_WATCHTOWER_DISABLE_DECONTAMINATE', 'Available', 0),
		('SAILOR_WATCHTOWER_DISABLE_HARVEST', 'OperationType', 'UNITOPERATION_HARVEST_RESOURCE'),
		('SAILOR_WATCHTOWER_DISABLE_HARVEST', 'Available', 0),
		('SAILOR_WATCHTOWER_DISABLE_FEATURE_REMOVAL', 'OperationType', 'UNITOPERATION_REMOVE_FEATURE'),
		('SAILOR_WATCHTOWER_DISABLE_FEATURE_REMOVAL', 'Available', 0);
END; 